### ISSUE TITLE
Deploy problems

### ISSUE THREAD

**Issue by michbil** [webRunes/Plus-WRIO-App#121]
Experiencing deploy problems, in Travis-CI logs:
```
Already up-to-date!
 HEAD detached at 9e8b101
nothing to commit, working directory clean
Dropped refs/stash@{0} (e1792e1899e648fa8eacb6422b2141d77679929b)
```
Here is few related links:
https://github.com/travis-ci/dpl/issues/207
http://docs.travis-ci.com/user/deployment/modulus/#Deploying-build-artifacts

**Comment by AlexeyAnshakov** [comment]
@michbil is it ready?

**Comment by michbil** [comment]
yes, you can close it
