### ISSUE TITLE
UI issue

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/Plus-WRIO-App#175]
При нажатии на "+" он неактивен.

**Comment by Xurma2** [comment]
Можно закрывать

**Comment by AlexeyAnshakov** [comment]
При нажатии на пункты правого меню, скролл в Plus прыгает вниз.

**Comment by AlexeyAnshakov** [comment]
При отсутствии названия для таба происходит наслоение следующего
![issue](https://cloud.githubusercontent.com/assets/604410/13666652/eac6664e-e6b2-11e5-98ec-fcdef9fffc29.png)
В случае отсутствия информации нужно называть таб "Untitled".

**Comment by AlexeyAnshakov** [comment]
страница открываются в разных табах
https://wr.io/122942999005/
https://wr.io/122942999005/index.html
надо чтобы в одном и том же (без index.html в url)

**Comment by AlexeyAnshakov** [comment]
В случае отсутствия имени таба отображать как "Untitled".
