### ISSUE TITLE
index. Reward 5 USD

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/Plus-WRIO-App#74]
Please open
>webrunes.com

and click on 
>Profile link

at the Login widget. You will get on user's profile page. Please update s3 config, so user's profiles opens properly without 
>/index.htm 

at the end. Because now Plus tab don't work for profiles, because look at
>http://webrunes.s3.amazonaws.com/User-ID-here

**Comment by umairadeeb** [comment]
This is done. But you will have to use a URL as mentioned in this document:
http://docs.aws.amazon.com/AmazonS3/latest/dev/HostingWebsiteOnS3Setup.html#step2-add-bucket-policy-make-content-public

Static website urls on S3 are supported in below format:
http://<bucket-name>.s3-website-<region>.amazonaws.com

In our case, its this:
http://webrunes.s3-website-us-east-1.amazonaws.com/1057217400/

**Comment by AlexeyAnshakov** [comment]
Thank you. URL has been updated.
