### ISSUE TITLE
Plus issues

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/Plus-WRIO-App#85]
*Expand/collapse должен работать при посещении страницы, не динамически. Т.е. при нажатии на родительский таб нужно переходить на его страницу, а не expand/collapse как это работало в предыдущей версии на сайте. В прототипе так сделано лишь для примера отображения состояний.
*в FF не отображается json-ld такст
*в IE и FF странный эффект при открытии страницы, сперва как будто увеличенная страница (и шрифты), которая после уменьшается до нормальных размеров, что создает неприятный эффект. Работает нормально при простой перезагрузке страницы через F5.
*в IE при переключении между 
http://webrunes.com/
и
http://wrioos.com/
меняются местами child в родительском табе "webRunes". Child должны отображаться исходя из своего физ. расположения в plus json-ld.
*child после удаления снова виден после перехода на др. страницу или F5
*parent должен оставаться после удаления всех child и быть с иконкой закрытия вместо цифр

**Comment by AlexeyAnshakov** [comment]
После мержа рендерится правое меню два раза

**Comment by AlexeyAnshakov** [comment]
Неправильное отображение
http://wrioos.com/
http://webgold.wrioos.com/
http://webrunes.com/blog.htm
и пр.
Не происходит добавление в меню новых пунктов при открытии страниц.

**Comment by spirinvladimir** [comment]
Нужно пересобрать WRIO-InternetOS. Чтобы увидеть обновленную версию.

1 июля 2015 г., 9:28 пользователь Alexey Anshakov <notifications@github.com>
написал:

**Comment by AlexeyAnshakov** [comment]
Пересобрал, но это не помогло.

**Comment by AlexeyAnshakov** [comment]
Показывать вложенные старницы лишь для активного таба

**Comment by AlexeyAnshakov** [comment]
Last PR broke Plus
